/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          colors: {
              "surface-tint": "#565e74",
              "surface": "#f8fafc",
              "surface-container-highest": "#e0e3e5",
              "inverse-surface": "#2d3133",
              "on-background": "#191c1e",
              "surface-container-low": "#f1f5f9",
              "surface-container-high": "#e6e8ea",
              "inverse-on-surface": "#eff1f3",
              "surface-container-lowest": "#ffffff",
              "surface-variant": "#e0e3e5",
              "background": "#f8fafc",
              "on-surface": "#191c1e",
              "on-surface-variant": "#45464d",
              "surface-dim": "#d8dadc",
              "outline": "#76777d",
              "outline-variant": "#c6c6cd",
              "error": "#ba1a1a",
              "on-error": "#ffffff",
              "error-container": "#ffdad6",
              "on-error-container": "#93000a",
              "primary": "#6b21a8",
              "on-primary": "#ffffff",
              "primary-container": "#f3e8ff",
              "on-primary-container": "#3b0764",
              "primary-fixed": "#e9d5ff",
              "on-primary-fixed": "#2b044d",
              "inverse-primary": "#d8b4fe",
              "secondary": "#0d9488",
              "on-secondary": "#ffffff",
              "secondary-container": "#ccfbf1",
              "on-secondary-container": "#115e59",
          },
          borderRadius: {
              "4xl": "2rem",
          },
          fontFamily: {
              "headline-md": ["Newsreader", "serif"],
              "body-md": ["Inter", "Manrope", "sans-serif"],
              "headline-lg": ["Newsreader", "serif"],
              "body-lg": ["Inter", "Manrope", "sans-serif"],
              "display-lg": ["Newsreader", "serif"],
              "label-md": ["Inter", "Manrope", "sans-serif"],
          },
          animation: {
              "fade-in-up": "fadeInUp 0.5s ease-out forwards",
              "fade-in": "fadeIn 0.4s ease-out forwards",
              "slide-in-left": "slideInLeft 0.4s ease-out forwards",
              "scale-in": "scaleIn 0.3s ease-out forwards",
              "float": "float 3s ease-in-out infinite",
              "pulse-glow": "pulse-glow 2s ease-in-out infinite",
          },
          boxShadow: {
              "glass": "0 8px 32px 0 rgba(31, 38, 135, 0.07)",
              "card": "0 1px 3px rgba(0,0,0,0.04), 0 6px 16px rgba(0,0,0,0.04)",
              "card-hover": "0 4px 12px rgba(0,0,0,0.08), 0 12px 28px rgba(0,0,0,0.06)",
              "glow-purple": "0 0 20px rgba(107,33,168,0.15)",
              "glow-teal": "0 0 20px rgba(13,148,136,0.15)",
          },
      },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
