import React, { forwardRef } from 'react';

const ResumePreview = forwardRef(({ data, template }, ref) => {
  const certs = (data.certifications || '').split('\n').filter(Boolean);
  const achievements = (data.achievements || '').split('\n').filter(Boolean);

  if (template === 'cmrit') return <CMRITTemplate ref={ref} data={data} certs={certs} achievements={achievements} />;
  if (template === 'fresher') return <FresherTemplate ref={ref} data={data} certs={certs} achievements={achievements} />;
  return <ATSTemplate ref={ref} data={data} certs={certs} achievements={achievements} />;
});

ResumePreview.displayName = 'ResumePreview';
export default ResumePreview;

// Helper to parse **bold** text generated by AI
const renderText = (text) => {
  if (!text) return null;
  const parts = text.split(/(\*\*.*?\*\*)/g);
  return parts.map((part, i) => 
    part.startsWith('**') && part.endsWith('**') 
      ? <strong key={i} className="font-bold text-black">{part.slice(2, -2)}</strong> 
      : part
  );
};

/* ───────────── CMRIT 2-Page Template (Strict Format) ───────────── */
const CMRITTemplate = forwardRef(({ data, certs, achievements }, ref) => {
  const cocurricular = (data.cocurricular || '').split('\n').filter(Boolean);
  
  return (
    <div ref={ref} className="p-8 leading-[1.15] text-black bg-white min-h-[1100px] text-justify break-words border-[1px] border-black m-2" style={{ fontFamily: '"Times New Roman", Times, serif', fontSize: '11.5pt' }}>
      <style>{`@media print { @page { size: A4; margin: 12.7mm; } }`}</style>
      
      <div className="mb-4">
        <h1 className="font-bold uppercase tracking-wider mb-2" style={{ fontSize: '12pt', margin: 0 }}>{data.name || 'YOUR NAME'}</h1>
        <div style={{ fontSize: '11.5pt', lineHeight: '1.2' }}>
          <div><span className="font-bold">Current Address:</span> {data.address}</div>
          <div><span className="font-bold">Mobile no:</span> {data.phone}</div>
          <div><span className="font-bold">Email:</span> {data.email}</div>
          <div><span className="font-bold">LinkedIn:</span> {data.linkedin}</div>
          <div><span className="font-bold">GitHub:</span> {data.github}</div>
          <div><span className="font-bold">LeetCode:</span> {data.leetcode}</div>
        </div>
      </div>

      {data.summary && (
        <Section title="CAREER OBJECTIVE" font="times">
          <p className="mt-1">{data.summary}</p>
        </Section>
      )}

      <Section title="EDUCATIONAL QUALIFICATION" font="times">
        <div className="space-y-3 mt-1">
          {data.education.filter(e => e.degree).map((e, i) => (
            <div key={i} className="break-inside-avoid">
              <ul className="list-disc ml-5 mt-1">
                <li className="pl-1">
                  <span className="font-bold">{e.degree}</span>, {e.institution}, {e.year}
                  {e.gpa && <span> ({e.gpa})</span>}
                </li>
              </ul>
            </div>
          ))}
        </div>
      </Section>

      {data.skills.length > 0 && (
        <Section title="TECHNICAL SKILLS" font="times">
          <ul className="list-disc ml-5 mt-1 space-y-1">
            {data.skills.map((s, i) => {
              const colonIdx = s.indexOf(':');
              if (colonIdx !== -1) {
                return (
                  <li key={i} className="pl-1">
                    <span className="font-bold">{s.substring(0, colonIdx + 1)}</span> {s.substring(colonIdx + 1).trim()}
                  </li>
                );
              }
              return <li key={i} className="pl-1">{s}</li>;
            })}
          </ul>
        </Section>
      )}

      <Section title="PROJECTS" font="times">
        <div className="space-y-3 mt-1">
          {data.projects && data.projects.filter(e => e.role).map((e, i) => (
            <div key={i} className="break-inside-avoid">
              <ul className="list-disc ml-5 mt-1" style={{ listStyleType: 'disc' }}>
                <li className="pl-1 font-bold">
                  {e.role}{e.company ? ` | ${e.company}` : ''}
                </li>
              </ul>
              <ul className="ml-10 mt-1 space-y-1" style={{ listStyleType: 'circle' }}>
                {e.bullets && e.bullets.filter(Boolean).slice(0, 5).map((b, j) => <li key={j} className="pl-1">{renderText(b)}</li>)}
              </ul>
            </div>
          ))}
        </div>
      </Section>

      {data.experience && data.experience.filter(e => e.role).length > 0 && (
        <Section title="INTERNSHIP" font="times">
          <div className="space-y-3 mt-1">
            {data.experience.filter(e => e.role).map((e, i) => (
              <div key={i} className="break-inside-avoid">
                <ul className="list-disc ml-5 mt-1" style={{ listStyleType: 'disc' }}>
                  <li className="pl-1 font-bold">
                    {e.role}{e.company ? ` - ${e.company}` : ''} | {e.duration}
                  </li>
                </ul>
                <ul className="ml-10 mt-1 space-y-1" style={{ listStyleType: 'circle' }}>
                  {e.bullets && e.bullets.filter(Boolean).map((b, j) => <li key={j} className="pl-1">{renderText(b)}</li>)}
                </ul>
              </div>
            ))}
          </div>
        </Section>
      )}

      {cocurricular.length > 0 && (
        <Section title="CO-CURRICULAR ACTIVITIES & EXTRA CURRICULAR ACTIVITIES" font="times">
          <ul className="list-disc ml-5 mt-1 space-y-1" style={{ listStyleType: 'disc' }}>
            {cocurricular.map((a, i) => (
              <li key={`cc-${i}`} className="pl-1 font-bold">
                {a.split(':')[0]}:
                {a.split(':')[1] && (
                  <ul className="ml-5 mt-1 font-normal" style={{ listStyleType: 'circle' }}>
                    <li>{a.split(':')[1].trim()}</li>
                  </ul>
                )}
              </li>
            ))}
          </ul>
        </Section>
      )}

      {(achievements.length > 0) && (
        <Section title="AWARDS & ACHIEVEMENTS" font="times">
          <ul className="list-disc ml-5 mt-1 space-y-1" style={{ listStyleType: 'disc' }}>
            {achievements.map((a, i) => <li key={`a-${i}`} className="pl-1">{a}</li>)}
          </ul>
        </Section>
      )}

      <Section title="PERSONAL DETAILS" font="times">
        <div className="mt-1 w-full" style={{ display: 'flex' }}>
          <div style={{ width: '200px' }} className="space-y-1">
            <div>Date of Birth</div>
            <div>Gender</div>
            <div>Nationality</div>
            <div>Permanent Address</div>
            <div>Linguistic Competency</div>
            <div>Hobbies</div>
          </div>
          <div className="space-y-1 flex-1">
            <div>: {data.dob}</div>
            <div>: {data.gender}</div>
            <div>: {data.nationality}</div>
            <div>: {data.permAddress}</div>
            <div>: {data.languages}</div>
            <div>: {data.hobbies}</div>
          </div>
        </div>
      </Section>
    </div>
  );
});
CMRITTemplate.displayName = 'CMRITTemplate';

/* ───────────── Startup / Fresher Template ───────────── */
const FresherTemplate = forwardRef(({ data, certs, achievements }, ref) => {
  const cocurricular = (data.cocurricular || '').split('\n').filter(Boolean);
  const leadership = cocurricular.filter(c => c.toLowerCase().includes('leadership') || c.toLowerCase().includes('president') || c.toLowerCase().includes('captain'));
  const otherActivities = cocurricular.filter(c => !leadership.includes(c));

  return (
    <div ref={ref} className="p-8 leading-[1.2] text-black bg-white min-h-[1100px] text-justify break-words border-[1px] border-gray-300 m-2" style={{ fontFamily: 'Calibri, sans-serif', fontSize: '11pt' }}>
      <style>{`@media print { @page { size: A4; margin: 12.7mm; } }`}</style>
      
      <div className="mb-4 text-center">
        <h1 className="font-bold uppercase tracking-widest text-black" style={{ fontSize: '16pt', margin: 0 }}>{data.name || 'FULL NAME'}</h1>
        <p className="text-gray-900 mt-1" style={{ fontSize: '11pt', margin: 0 }}>
          {[data.address, data.email, data.phone, data.linkedin, data.github, data.leetcode].filter(Boolean).join(' | ')}
        </p>
      </div>

      {data.summary && (
        <Section title="CAREER OBJECTIVE" font="calibri">
          <p className="mt-1 text-gray-900 text-justify">{data.summary}</p>
        </Section>
      )}

      <Section title="ACADEMIC DETAILS" font="calibri">
        <div className="space-y-3 mt-1">
          {data.education.filter(e => e.degree).map((e, i) => (
            <div key={i} className="break-inside-avoid">
              <div className="font-bold text-black">{e.degree}</div>
              <div className="text-gray-900">
                {e.institution} | {e.gpa || 'CGPA'} | {e.year}
              </div>
            </div>
          ))}
        </div>
      </Section>

      {data.skills.length > 0 && (
        <Section title="TECHNICAL SKILLS" font="calibri">
          <ul className="mt-1 space-y-1 text-gray-900 list-disc ml-5">
            {data.skills.map((s, i) => {
              const colonIdx = s.indexOf(':');
              if (colonIdx !== -1) {
                return (
                  <li key={i} className="pl-1">
                    <span className="font-bold">{s.substring(0, colonIdx + 1)}</span> {s.substring(colonIdx + 1).trim()}
                  </li>
                );
              }
              return <li key={i} className="pl-1">{s}</li>;
            })}
          </ul>
        </Section>
      )}

      <Section title="PROJECTS" font="calibri">
        <div className="space-y-4 mt-1">
          {data.projects && data.projects.filter(e => e.role).map((e, i) => (
            <div key={i} className="break-inside-avoid">
              <div className="font-bold text-black uppercase">{e.role}</div>
              <ul className="ml-5 mt-1 space-y-1 text-gray-900" style={{ listStyleType: 'circle' }}>
                <li className="pl-1">Created / Developed / Utilised / Implemented: {e.bullets && e.bullets[0] ? renderText(e.bullets[0]) : ''}</li>
                <li className="pl-1">Tools & Technologies used: {e.company}</li>
                <li className="pl-1">Role: {e.bullets && e.bullets[1] ? renderText(e.bullets[1]) : ''}</li>
              </ul>
            </div>
          ))}
        </div>
      </Section>

      {otherActivities.length > 0 && (
        <Section title="CO-CURRICULAR & EXTRA-CURRICULAR ACTIVITIES" font="calibri">
          <ul className="mt-1 space-y-1 text-gray-900 list-disc ml-5">
            {otherActivities.map((a, i) => <li key={`cc-${i}`}>{a}</li>)}
          </ul>
        </Section>
      )}

      {leadership.length > 0 && (
        <Section title="LEADERSHIP SKILLS" font="calibri">
          <ul className="mt-1 space-y-1 text-gray-900 list-disc ml-5">
            {leadership.map((l, i) => <li key={`l-${i}`}>{l}</li>)}
          </ul>
        </Section>
      )}

      {(achievements.length > 0 || certs.length > 0) && (
        <Section title="ACHIEVEMENTS" font="calibri">
          <ul className="mt-1 space-y-1 text-gray-900 list-disc ml-5">
            {achievements.map((a, i) => <li key={`a-${i}`}>{a}</li>)}
            {certs.map((c, i) => <li key={`c-${i}`}>{c}</li>)}
          </ul>
        </Section>
      )}
    </div>
  );
});
FresherTemplate.displayName = 'FresherTemplate';

/* ───────────── STRICT ATS DEFAULT TEMPLATE ───────────── */
const ATSTemplate = forwardRef(({ data, certs, achievements }, ref) => (
  <div ref={ref} className="p-8 font-['Arial',sans-serif] text-[11pt] leading-[1.3] text-black bg-white min-h-[1100px] text-left border-[1px] border-black m-2">
    <style>{`@media print { @page { size: A4; margin: 1 inch; } }`}</style>
    
    <div className="text-center mb-6">
      <h1 className="text-[16pt] font-bold uppercase tracking-wide" style={{ margin: 0 }}>{data.name || 'YOUR NAME'}</h1>
      <p className="text-[11pt] mt-1" style={{ margin: 0 }}>
        {[data.email, data.phone, data.linkedin, data.github].filter(Boolean).join(' | ')}
      </p>
    </div>
    
    {data.summary && (
      <Section title="CAREER OBJECTIVE" font="arial">
        <p className="mt-2 text-justify">{data.summary}</p>
      </Section>
    )}

    <Section title="EDUCATION" font="arial">
      <div className="space-y-3 mt-2">
        {data.education.filter(e => e.degree).map((e, i) => (
          <div key={i} className="break-inside-avoid" style={{ display: 'flex', justifyContent: 'space-between' }}>
            <div><span className="font-bold">{e.degree}</span> — {e.institution}</div>
            <div>{e.year}{e.gpa ? ` | ${e.gpa}` : ''}</div>
          </div>
        ))}
      </div>
    </Section>
    
    {data.skills.length > 0 && (
      <Section title="TECHNICAL SKILLS" font="arial">
        <ul className="list-disc ml-5 mt-1 space-y-1">
          {data.skills.map((s, i) => {
            const colonIdx = s.indexOf(':');
            if (colonIdx !== -1) {
              return (
                <li key={i} className="pl-1">
                  <span className="font-bold">{s.substring(0, colonIdx + 1)}</span> {s.substring(colonIdx + 1).trim()}
                </li>
              );
            }
            return <li key={i} className="pl-1">{s}</li>;
          })}
        </ul>
      </Section>
    )}
    
    <Section title="WORK EXPERIENCE" font="arial">
      <div className="space-y-4 mt-2">
        {data.experience.filter(e => e.role).map((e, i) => (
          <div key={i} className="break-inside-avoid">
            <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 'bold' }}>
              <span>{e.role}{e.company ? ` — ${e.company}` : ''}</span>
              <span>{e.duration}</span>
            </div>
            <ul className="list-disc ml-5 mt-1.5 space-y-1">
              {e.bullets.filter(Boolean).map((b, j) => <li key={j} className="pl-1">{renderText(b)}</li>)}
            </ul>
          </div>
        ))}
      </div>
    </Section>

    {data.projects && data.projects.filter(e => e.role).length > 0 && (
      <Section title="PROJECTS" font="arial">
        <div className="space-y-4 mt-2">
          {data.projects.filter(e => e.role).map((e, i) => (
            <div key={i} className="break-inside-avoid">
              <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 'bold' }}>
                <span>{e.role}{e.company ? ` — ${e.company}` : ''}</span>
              </div>
              <ul className="list-disc ml-5 mt-1.5 space-y-1">
                {e.bullets.filter(Boolean).map((b, j) => <li key={j} className="pl-1">{renderText(b)}</li>)}
              </ul>
            </div>
          ))}
        </div>
      </Section>
    )}
    
    {(certs.length > 0 || achievements.length > 0) && (
      <Section title="ACHIEVEMENTS" font="arial">
        <ul className="list-disc ml-5 mt-2 space-y-1">
          {achievements.map((a, i) => <li key={`a-${i}`} className="pl-1">{a}</li>)}
          {certs.map((c, i) => <li key={`c-${i}`} className="pl-1">{c}</li>)}
        </ul>
      </Section>
    )}
  </div>
));
ATSTemplate.displayName = 'ATSTemplate';

/* ───── Shared helpers ───── */
function Section({ title, children, font }) {
  let fontFamily = 'Arial, sans-serif';
  if (font === 'times') fontFamily = '"Times New Roman", Times, serif';
  if (font === 'calibri') fontFamily = 'Calibri, sans-serif';

  return (
    <div className="mb-5 break-inside-avoid" style={{ fontFamily }}>
      <h2 className="uppercase tracking-wider mb-2 pb-1 text-black" style={{ fontSize: '12pt', fontWeight: 'bold', borderBottom: '1px solid black', margin: 0 }}>
        {title}
      </h2>
      {children}
    </div>
  );
}
